server:
  port: 8888


spring:
  application:
    name: OAUTH

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-id:
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            #redirect-uri: "{baseUrl}/{action}/oauth2/callback/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email

          naver:
            client-name: Naver
            client-id:
            client-secret:
            #redirect-uri: "{baseUrl}/{action}/oauth2/callback/{registrationId}"
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}" # (== http://localhost:8080/login/oauth2/code/naver)
            authorization-grant-type: authorization_code
            scope: name, email

          google:
            client-name: google
            client-id:
            client-secret: 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
            #default http://localhost:8080/login/oauth2/code/google
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - email
              - profile

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize    #??? login Page
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize   #naver login Page
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


  data:
    mongodb:
      database: test
      host: localhost
      port: 27017
      auto-index-creation: true


app:
  jwt:
    secretKey: 00000-000000-00000-00000-00000-00000  # 256 < size
    ACCESS_TOKEN_EXPIRE_TIME: 1800000    # 1000 * 60 * 30   30?
    REFRESH_TOKEN_EXPIRE_TIME: 3600000   # 1000 * 60 * 60   60?
